use yr789; 
DROP TABLE IF EXISTS institutions_info; 
CREATE TABLE institutions_info (
	id BIGINT,
	user_base_id VARCHAR(400),
	enterprise_name VARCHAR(400),
	organization_code VARCHAR(400),
	tax_registration_no VARCHAR(400),
	business_license_no VARCHAR(400),
	business_license_province VARCHAR(400),
	business_license_city VARCHAR(400),
	commonly_used_address VARCHAR(400),
	business_period VARCHAR(400),
	legal_representative_name VARCHAR(400),
	legal_representative_card_no VARCHAR(400),
	business_license_path VARCHAR(400),
	business_license_cachet_path VARCHAR(400),
	cert_front_path VARCHAR(400),
	cert_back_path VARCHAR(400),
	opening_license_path VARCHAR(400),
	bank_open_name VARCHAR(400),
	bank_card_no VARCHAR(400),
	bank_type VARCHAR(400),
	bank_key VARCHAR(400),
	bank_province VARCHAR(400),
	bank_city VARCHAR(400),
	bank_address VARCHAR(400),
	institutions_in_code VARCHAR(400),
	institutions_them_roughly VARCHAR(400),
	referees VARCHAR(400),
	contact_name VARCHAR(400),
	company_phone VARCHAR(400),
	legal_representative_card_period VARCHAR(400),
	contact_cert_no VARCHAR(400),
	zip_code VARCHAR(400),
	user_id BIGINT,
	user_name VARCHAR(400),
	log_password VARCHAR(400),
	pay_password VARCHAR(400),
	account_id VARCHAR(400),
	account_name VARCHAR(400),
	mobile VARCHAR(400),
	mobile_binding VARCHAR(400),
	mail VARCHAR(400),
	mail_binding VARCHAR(400),
	type VARCHAR(400),
	state VARCHAR(400),
	row_add_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
	row_update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP  ON UPDATE CURRENT_TIMESTAMP ,
	identity_name VARCHAR(400),
	identity_start_no VARCHAR(400),
	identity_end_no VARCHAR(400),
	ex_identity_no VARCHAR(400),
	real_name_authentication VARCHAR(400)
);