use yr789; 
DROP TABLE IF EXISTS personal_info; 
CREATE TABLE personal_info (
	id BIGINT,
	user_base_id VARCHAR(400),
	real_name VARCHAR(400),
	cert_no VARCHAR(400),
	business_period VARCHAR(400),
	cert_front_path VARCHAR(400),
	cert_back_path VARCHAR(400),
	bank_open_name VARCHAR(400),
	bank_card_no VARCHAR(400),
	bank_type VARCHAR(400),
	bank_key VARCHAR(400),
	bank_province VARCHAR(400),
	bank_city VARCHAR(400),
	bank_address VARCHAR(400),
	gender INT,
	referees VARCHAR(400),
	customer_source VARCHAR(400),
	member_no VARCHAR(400),
	role_id int,
	user_id BIGINT,
	user_name VARCHAR(400),
	account_id VARCHAR(400),
	account_name VARCHAR(400),
	mobile VARCHAR(400),
	mobile_binding VARCHAR(400),
	mail VARCHAR(400),
	mail_binding VARCHAR(400),
	type VARCHAR(400),
	state VARCHAR(400),
	row_add_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
	row_update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP  ON UPDATE CURRENT_TIMESTAMP ,
	real_name_authentication VARCHAR(400)
);